spring.application.name: gateway
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: true
#server.port: 8761
eureka.client.service-url.defaultZone: http://localhost:8080/eureka
eureka.server.wait-time-in-ms-when-sync-empty: 0
zuul.prefix: /api

#zuul.routes.middleware.path: /equipment/**
#zuul.routes.middleware.url: http://localhost:8081/
# http://localhost:8080/api/employee/v1/employee/list

zuul:
  routes:
    employee:
      path: /employee/**
      serviceId: employee
      #url: http://localhost:8081/
    equipment:
      path: /equipment/**
      serviceId: equipment

#spring.data.mongodb.authentication-database: admin
#spring.data.mongodb.username: root
#spring.data.mongodb.password: root
spring.data.mongodb.database: test
spring.data.mongodb.port: 27017
spring.data.mongodb.host: localhost